### ISSUE TITLE
Add Mac OS support with Multipass

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/deployment-configs#316]
We should modify our qa-script to allow Mac users (or just for @carkod xD) to run our deployments locally using Multipass.

One option could be to pass the konf.py output to kubectl but for some reason, the following doesn't work:
```
./konf.py production sites/canonical.com.yaml | multipass exec ubuntu-lts -- microk8s.kubectl apply -f -
```

Strangely the following does work as expected:
```
./konf.py production sites/canonical.com.yaml | multipass exec ubuntu-lts -- cat
```

**Comment by jkfran** [comment]
@nottrobin has proposed to use:
```
./konf.py production sites/canonical.com.yaml | multipass transfer - microk8s-vm:canonical.com.yaml
multipass exec microk8s-vm -- /snap/bin/microk8s.kubectl apply -f canonical.com.yaml
```

**Comment by nottrobin** [comment]
It looks like the underlying issue might have been fixed in https://github.com/canonical/multipass/issues/1217 - and since it looks like the PR that closed that was only merged 21 days ago, we might just be waiting for the fix to when it's way out to the stable release.

We should keep trying the more succinct way to see if it starts to work soon.

**Comment by jkfran** [comment]
@nottrobin I think now there is no need to use multipass for this. Microk8s now support Mac OS.

Maybe we can close this issue. It would be nice if @carkod can try Microk8s and the Konf script in his system?

**Comment by nottrobin** [comment]
I think @carkod already tried it and it worked, is that right? Anyway, I think you're right. This can probably be closed.

**Comment by carkod** [comment]
This is working already
